### ISSUE TITLE
Crash at start on Android

### ISSUE THREAD

**Issue by LouisDuboscq** [alexzhirkevich/compose-look-and-feel#4]
Hello, 

First of all thank you for this repository which is excellent.

I can't make it running on all my Android, either physical or simulators. It crashes at start. It works fine on iOS. 

Here is the problem : 

`Process: com.myapplication.MyApplication, PID: 31222
                                                                             java.lang.NoSuchMethodError: No virtual method textFieldColors-l59Burw(JJJJJLandroidx/compose/foundation/text/selection/TextSelectionColors;JJJJJJJJJJJJJJJJJJJJJJLandroidx/compose/runtime/Composer;IIII)Landroidx/compose/material3/TextFieldColors; in class Landroidx/compose/material3/TextFieldDefaults; or its super classes (declaration of 'androidx.compose.material3.TextFieldDefaults' appears in /data/app/~~qzAoIGcV9sAe6nS6CQvbog==/com.myapplication.MyApplication-IZWLvGUDL8YXauFwf7GS_w==/base.apk)
                                                                             	at com.github.alexzhirkevich.lookandfeel.components.cupertino.CupertinoSearchTextFieldKt.cupertinoTextFieldColors-GyCwops(CupertinoSearchTextField.kt:91)
                                                                             	at com.github.alexzhirkevich.lookandfeel.components.cupertino.CupertinoSearchTextFieldKt.CupertinoSearchTextField(CupertinoSearchTextField.kt:167)
                                                                             	at AppKt$ScaffoldSample$2.invoke(App.kt:233)
                                                                             	at AppKt$ScaffoldSample$2.invoke(App.kt:208)`

**Comment by alexzhirkevich** [comment]
Hi. Library is in early development phase and is not ready to use
